name: madres_digitales_flutter_new
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State Management
  flutter_riverpod: ^2.6.1

  # Networking
  dio: ^5.4.0
  http: ^1.1.0

  # JSON & Serialization
  json_annotation: ^4.8.1

  # Functional Programming
  dartz: ^0.10.1
  equatable: ^2.0.5

  # Navigation
  go_router: ^16.2.4

  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Location & Maps
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  flutter_map: ^8.2.2
  latlong2: 0.9.1

  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  fl_chart: ^0.68.0
  pull_to_refresh: ^2.0.0
  gap: ^3.0.1

  # Utilities
  connectivity_plus: ^7.0.0
  uuid: ^4.2.1
  image_picker: ^1.0.4
  intl: ^0.19.0
  logger: ^2.6.1

  # Notifications
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1

  # Audio
  audioplayers: ^5.2.1

  # Video
  video_player: ^2.8.1

  # Other
  url_launcher: ^6.2.1
  package_info_plus: ^8.3.1
  socket_io_client: ^2.0.3+1
  file_picker: ^8.0.0+1
  wakelock_plus: ^1.3.3
  jwt_decoder: ^2.0.1
  share_plus: ^10.1.3
  chewie: ^1.8.5
  flutter_pdfview: ^1.3.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  riverpod_generator: ^2.4.0
  riverpod_annotation: ^2.6.1
  custom_lint: ^0.6.3
  riverpod_lint: ^2.3.7
  mockito: ^5.4.4
  build_test: ^2.1.7
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
