DELETE FROM public.control_prenatal WHERE gestante_id IS NULL OR fecha_control IS NULL;
UPDATE public.control_prenatal
SET semanas_gestacion = COALESCE(semanas_gestacion, 0),
    peso = COALESCE(peso, 0),
    altura_uterina = COALESCE(altura_uterina, 0),
    presion_sistolica = COALESCE(presion_sistolica, 0),
    presion_diastolica = COALESCE(presion_diastolica, 0),
    frecuencia_cardiaca = COALESCE(frecuencia_cardiaca, 0),
    frecuencia_respiratoria = COALESCE(frecuencia_respiratoria, 0),
    temperatura = COALESCE(temperatura, 0),
    movimientos_fetales = COALESCE(movimientos_fetales, ''),
    edemas = COALESCE(edemas, ''),
    proteinuria = COALESCE(proteinuria, ''),
    glucosuria = COALESCE(glucosuria, ''),
    hallazgos = COALESCE(hallazgos, '{}'::jsonb),
    recomendaciones = COALESCE(recomendaciones, ''),
    proximo_control = COALESCE(proximo_control, CURRENT_TIMESTAMP),
    realizado = COALESCE(realizado, false),
    observaciones = COALESCE(observaciones, ''),
    examenes_solicitados = COALESCE(examenes_solicitados, '[]'::jsonb),
    resultados_examenes = COALESCE(resultados_examenes, '[]'::jsonb),
    fecha_actualizacion = COALESCE(fecha_actualizacion, CURRENT_TIMESTAMP);

DELETE FROM public.alertas WHERE gestante_id IS NULL OR tipo_alerta IS NULL OR nivel_prioridad IS NULL OR mensaje IS NULL;
UPDATE public.alertas
SET sintomas = COALESCE(sintomas, '[]'::jsonb),
    coordenadas_alerta = COALESCE(coordenadas_alerta, '{}'::jsonb),
    resuelta = COALESCE(resuelta, false),
    fecha_resolucion = COALESCE(fecha_resolucion, NULL),
    generado_por_id = COALESCE(generado_por_id, ''),
    fecha_creacion = COALESCE(fecha_creacion, CURRENT_TIMESTAMP),
    fecha_actualizacion = COALESCE(fecha_actualizacion, CURRENT_TIMESTAMP),
    created_at = COALESCE(created_at, CURRENT_TIMESTAMP),
    estado = COALESCE(estado, 'pendiente'),
    es_automatica = COALESCE(es_automatica, false),
    score_riesgo = COALESCE(score_riesgo, 0),
    ubicacion_lat = COALESCE(ubicacion_lat, 0),
    ubicacion_lng = COALESCE(ubicacion_lng, 0),
    ubicacion_precision = COALESCE(ubicacion_precision, 0),
    nombre_madrina = COALESCE(nombre_madrina, ''),
    telefono_madrina = COALESCE(telefono_madrina, ''),
    nombre_gestante = COALESCE(nombre_gestante, ''),
    telefono_gestante = COALESCE(telefono_gestante, ''),
    direccion_gestante = COALESCE(direccion_gestante, ''),
    municipio = COALESCE(municipio, '');