// Mocks generated by Mockito 5.4.6 from annotations
// in madres_digitales_flutter_new/test/features/contenido/domain/usecases/get_contenidos_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:madres_digitales_flutter_new/core/errors/app_error.dart' as _i6;
import 'package:madres_digitales_flutter_new/core/types/result.dart' as _i2;
import 'package:madres_digitales_flutter_new/features/contenido/domain/entities/categoria.dart'
    as _i7;
import 'package:madres_digitales_flutter_new/features/contenido/domain/entities/contenido.dart'
    as _i5;
import 'package:madres_digitales_flutter_new/features/contenido/domain/repositories/contenido_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T, E> extends _i1.SmartFake implements _i2.Result<T, E> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ContenidoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockContenidoRepository extends _i1.Mock
    implements _i3.ContenidoRepository {
  MockContenidoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i5.Contenido>, _i6.AppError>> getContenidos({
    _i5.CategoriaContenido? categoria,
    _i5.TipoContenido? tipo,
    _i5.NivelDificultad? nivel,
    int? page = 1,
    int? limit = 20,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getContenidos,
          [],
          {
            #categoria: categoria,
            #tipo: tipo,
            #nivel: nivel,
            #page: page,
            #limit: limit,
            #forceRefresh: forceRefresh,
          },
        ),
        returnValue:
            _i4.Future<_i2.Result<List<_i5.Contenido>, _i6.AppError>>.value(
                _FakeResult_0<List<_i5.Contenido>, _i6.AppError>(
          this,
          Invocation.method(
            #getContenidos,
            [],
            {
              #categoria: categoria,
              #tipo: tipo,
              #nivel: nivel,
              #page: page,
              #limit: limit,
              #forceRefresh: forceRefresh,
            },
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Contenido>, _i6.AppError>>);

  @override
  _i4.Future<_i2.Result<_i5.Contenido?, _i6.AppError>> getContenidoById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getContenidoById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.Contenido?, _i6.AppError>>.value(
            _FakeResult_0<_i5.Contenido?, _i6.AppError>(
          this,
          Invocation.method(
            #getContenidoById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.Contenido?, _i6.AppError>>);

  @override
  _i4.Future<_i2.Result<_i5.Contenido, _i6.AppError>> createContenido({
    required String? titulo,
    required String? descripcion,
    required _i5.CategoriaContenido? categoria,
    required _i5.TipoContenido? tipo,
    String? url,
    String? thumbnailUrl,
    int? duracion,
    _i5.NivelDificultad? nivel = _i5.NivelDificultad.basico,
    List<String>? etiquetas = const [],
    int? semanaGestacionInicio,
    int? semanaGestacionFin,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createContenido,
          [],
          {
            #titulo: titulo,
            #descripcion: descripcion,
            #categoria: categoria,
            #tipo: tipo,
            #url: url,
            #thumbnailUrl: thumbnailUrl,
            #duracion: duracion,
            #nivel: nivel,
            #etiquetas: etiquetas,
            #semanaGestacionInicio: semanaGestacionInicio,
            #semanaGestacionFin: semanaGestacionFin,
          },
        ),
        returnValue: _i4.Future<_i2.Result<_i5.Contenido, _i6.AppError>>.value(
            _FakeResult_0<_i5.Contenido, _i6.AppError>(
          this,
          Invocation.method(
            #createContenido,
            [],
            {
              #titulo: titulo,
              #descripcion: descripcion,
              #categoria: categoria,
              #tipo: tipo,
              #url: url,
              #thumbnailUrl: thumbnailUrl,
              #duracion: duracion,
              #nivel: nivel,
              #etiquetas: etiquetas,
              #semanaGestacionInicio: semanaGestacionInicio,
              #semanaGestacionFin: semanaGestacionFin,
            },
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.Contenido, _i6.AppError>>);

  @override
  _i4.Future<_i2.Result<_i5.Contenido, _i6.AppError>> updateContenido(
    String? id, {
    String? titulo,
    String? descripcion,
    _i5.CategoriaContenido? categoria,
    _i5.TipoContenido? tipo,
    String? url,
    String? thumbnailUrl,
    int? duracion,
    _i5.NivelDificultad? nivel,
    List<String>? etiquetas,
    int? semanaGestacionInicio,
    int? semanaGestacionFin,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateContenido,
          [id],
          {
            #titulo: titulo,
            #descripcion: descripcion,
            #categoria: categoria,
            #tipo: tipo,
            #url: url,
            #thumbnailUrl: thumbnailUrl,
            #duracion: duracion,
            #nivel: nivel,
            #etiquetas: etiquetas,
            #semanaGestacionInicio: semanaGestacionInicio,
            #semanaGestacionFin: semanaGestacionFin,
          },
        ),
        returnValue: _i4.Future<_i2.Result<_i5.Contenido, _i6.AppError>>.value(
            _FakeResult_0<_i5.Contenido, _i6.AppError>(
          this,
          Invocation.method(
            #updateContenido,
            [id],
            {
              #titulo: titulo,
              #descripcion: descripcion,
              #categoria: categoria,
              #tipo: tipo,
              #url: url,
              #thumbnailUrl: thumbnailUrl,
              #duracion: duracion,
              #nivel: nivel,
              #etiquetas: etiquetas,
              #semanaGestacionInicio: semanaGestacionInicio,
              #semanaGestacionFin: semanaGestacionFin,
            },
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.Contenido, _i6.AppError>>);

  @override
  _i4.Future<_i2.Result<void, _i6.AppError>> deleteContenido(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteContenido,
          [id],
        ),
        returnValue: _i4.Future<_i2.Result<void, _i6.AppError>>.value(
            _FakeResult_0<void, _i6.AppError>(
          this,
          Invocation.method(
            #deleteContenido,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Result<void, _i6.AppError>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Contenido>, _i6.AppError>> searchContenidos(
    String? query, {
    _i5.CategoriaContenido? categoria,
    _i5.TipoContenido? tipo,
    _i5.NivelDificultad? nivel,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchContenidos,
          [query],
          {
            #categoria: categoria,
            #tipo: tipo,
            #nivel: nivel,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<_i2.Result<List<_i5.Contenido>, _i6.AppError>>.value(
                _FakeResult_0<List<_i5.Contenido>, _i6.AppError>(
          this,
          Invocation.method(
            #searchContenidos,
            [query],
            {
              #categoria: categoria,
              #tipo: tipo,
              #nivel: nivel,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Contenido>, _i6.AppError>>);

  @override
  _i4.Future<void> toggleFavorito(String? contenidoId) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorito,
          [contenidoId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> registrarVista(String? contenidoId) => (super.noSuchMethod(
        Invocation.method(
          #registrarVista,
          [contenidoId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> actualizarProgreso(
    String? contenidoId, {
    int? tiempoVisualizado,
    double? porcentaje,
    bool? completado,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #actualizarProgreso,
          [contenidoId],
          {
            #tiempoVisualizado: tiempoVisualizado,
            #porcentaje: porcentaje,
            #completado: completado,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Contenido>> getFavoritos(String? usuarioId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoritos,
          [usuarioId],
        ),
        returnValue: _i4.Future<List<_i5.Contenido>>.value(<_i5.Contenido>[]),
      ) as _i4.Future<List<_i5.Contenido>>);

  @override
  _i4.Future<List<_i5.Contenido>> getContenidosConProgreso(String? usuarioId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getContenidosConProgreso,
          [usuarioId],
        ),
        returnValue: _i4.Future<List<_i5.Contenido>>.value(<_i5.Contenido>[]),
      ) as _i4.Future<List<_i5.Contenido>>);

  @override
  _i4.Future<List<_i7.Categoria>> getCategorias() => (super.noSuchMethod(
        Invocation.method(
          #getCategorias,
          [],
        ),
        returnValue: _i4.Future<List<_i7.Categoria>>.value(<_i7.Categoria>[]),
      ) as _i4.Future<List<_i7.Categoria>>);

  @override
  _i4.Future<void> clearCache({_i5.CategoriaContenido? categoria}) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
          {#categoria: categoria},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
